### ISSUE TITLE
List of generators empty

### ISSUE THREAD

**Issue by schroding3rscat** [SamVerschueren/vscode-yo#15]
After extension installation no generators displayed. 
![ode](https://cloud.githubusercontent.com/assets/3431598/11272229/6b175a6c-8edc-11e5-94db-1687459544b9.gif)
I tried to reinstall extension, but nothing helps. 

**Visual Studio Code** 
Version 0.10.1 
Commit df352367df2efcfa9d602d471e4e2f42140a0f05 
Date 2015-11-17T15:25:33.342Z 
Shell 0.34.1 
Renderer 45.0.2454.85 
Node 4.1.1 

**yo** 0.4.0

**Comment by SamVerschueren** [comment]
It's windows probably? And you're sure you have generators installed? Will test it asap. Thanks for reporting.

**Comment by schroding3rscat** [comment]
No, I didn't installed any generators manually. I thought that they will be downloaded like extensions. How do I install them?

**Comment by SamVerschueren** [comment]
Depends on what generator you want :).

For instance:

```
$ npm install -g generator-nm
```

Will install the [nm](https://github.com/sindresorhus/generator-nm) generator. Let me know if it works.

**Comment by SamVerschueren** [comment]
Closing this issue, reopen if you still experience the issues.
