### ISSUE TITLE
Unable to run sub generators

### ISSUE THREAD

**Issue by neoGeneva** [SamVerschueren/vscode-yo#16]
[generator-aspnet](https://github.com/OmniSharp/generator-aspnet#sub-generators) has quite a useful sub generators, it'd be useful to be able to run those from within Code.

**Comment by SamVerschueren** [comment]
This would definitely be a nice addition! Not sure how I would implement arguments though, like [aspnet:Class](https://github.com/OmniSharp/generator-aspnet#class).

@david-driscoll How do you do that in `atom-yeoman`?

**Comment by SamVerschueren** [comment]
@david-driscoll Already found out how you do it (https://github.com/david-driscoll/atom-yeoman/blob/master/lib/generator.ts#L263). Kinda hacky, not sure if there are better ways though.

**Comment by SamVerschueren** [comment]
@neoGeneva Upgrade to `0.6.0` and you will be able to run sub-generators :).

**Comment by neoGeneva** [comment]
@SamVerschueren works great, thanks!
