### ISSUE TITLE
Extension calls process.exit() 

### ISSUE THREAD

**Issue by bpasero** [SamVerschueren/vscode-yo#23]
I noticed that your extension (probably Yo itself) is calling process.exit() at some point. I know some node JS libraries tent to abuse process.exit() as a way to do flow control in their program. I see this happening when I abort Yo after it found a conflict when applying file changes.

In the future VS Code will ignore process.exit() calls because otherwise the extension host goes down and you would have to restart VS Code. 

I wonder how Atom behaves here I am sure they have the same problem, do you happen to know?

Not sure you can do anything about it but if Yo claims to be pluggable, they must also provide a way to avoid process.exit(). In fact, they should not even use it at all.

**Comment by SamVerschueren** [comment]
Any thoughts @sindresorhus @SBoudrias?

**Comment by SBoudrias** [comment]
The only place yeoman is calling `process.exit()` is effectively when the user select the `abort` option during a conflict. We should probably change this, feel free to open an issue on the yeoman/generator repo to discuss alternative further.

**Comment by bpasero** [comment]
I wonder if this causes Atom to just exit ;)

**Comment by SamVerschueren** [comment]
I don't think the diffing is implemented by `atom-yeoman`

// @david-driscoll

**Comment by SamVerschueren** [comment]
@bpasero Are you creating a new issue in `yeoman/generator` or should I do it?

**Comment by bpasero** [comment]
@SamVerschueren please go ahead and file it, thanks!

**Comment by SamVerschueren** [comment]
This was fixed and released in `0.22.1` of the [yeoman-generator](https://github.com/yeoman/generator). Generators that are not updated to this release will still call `process.exit()` instead of throwing an `AbortedError`.
