### ISSUE TITLE
Sub-generator input box not shown

### ISSUE THREAD

**Issue by Codenator81** [SamVerschueren/vscode-yo#24]
When try generate asp.net Class not get options for name of Class but just run it without name of Class

Yo version 0.7.0

**Comment by SamVerschueren** [comment]
Confirmed, fixing this ASAP.

**Comment by SamVerschueren** [comment]
Fix is blocked by https://github.com/Microsoft/vscode/issues/693

**Comment by SamVerschueren** [comment]
@Codenator81 Fixed in `v0.7.1`
