### ISSUE TITLE
How do Yeoman generators get resolved?

### ISSUE THREAD

**Issue by daviwil** [SamVerschueren/vscode-yo#37]
We'd like to hook up a Yeoman generator so that users of the [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) can easily create new PowerShell projects.  What do we need to do have our generator show up in the quick pick list?

Does your generator resolution depend on the workspace itself having a package.json file with the generator installed as a dependency?  Is there any way that our extension could include the generator so that it shows up in the list without the workspace needing a package.json?

Thanks!

cc @rkeithhill

**Comment by SamVerschueren** [comment]
Generators installed globally on the system (`npm install -g`) should be picked up automatically.

**Comment by daviwil** [comment]
Thanks Sam!

**Comment by SamVerschueren** [comment]
No problem :)
