### ISSUE TITLE
package.json is missing postinstall script

### ISSUE THREAD

**Issue by bpasero** [SamVerschueren/vscode-yo#38]
Any reason why the postinstall script is not configured for package.json:

`"postinstall": "node ./node_modules/vscode/bin/install"`

If you do not use this, otherwise the vscode module cannot be resolved because vscode.d.ts is missing unless you have this postinstall script.

**Comment by SamVerschueren** [comment]
You're right. It's possibly because in the beginning it wasn't necessary, right?

**Comment by bpasero** [comment]
@SamVerschueren yes for vscode@0.10.x it is not but I noticed that you use "*" as dependency and anyone checking out the project fresh and doing a npm install will get compile errors due to that.

**Comment by SamVerschueren** [comment]
Fixed! Thanks @bpasero

**Comment by bpasero** [comment]
Nice :+1:
